name: air_tinder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider:
  intl:
  google_fonts:
  tcard: ^1.3.5
  firebase_auth:
  firebase_core:
  cloud_firestore:
  firebase_storage:
  another_flushbar:
  lottie:
  image_picker:
  get_storage:
  uuid:
  amadeus_flutter: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:

  uses-material-design: true
  assets:
    -  assets/images/

