import 'package:air_tinder/view/bottom_nav_bar/bottom_nav_bar.dart';
import 'package:flutter/material.dart';

class FlightNumberDetailsProvider with ChangeNotifier {
  var samplevar;
  TextEditingController airlineCon = TextEditingController();
  TextEditingController departureDateCon = TextEditingController();
  DateTime departureDate = DateTime.now();
  String selectedAirline = "ABSA";
  // List<Map<String, String>> airlines = [
  //   {"ABSA": "M3"},
  //   {"ANA All Nippon Cargo": "NH"},
  //   {"Adria Airways": "JP"},
  //   {"Aegean Airlines": "A3"},
  //   {"Aer Lingus Cargo": "EI"},
  //   {"AeroUnion": "6R"},
  //   {"Aeroflot": "SU"},
  //   {"Aeromexico Cargo": "AM"},
  //   {"Aeromexpress Cargo": "QO"},
  //   {"Aerosvit": "VV"},
  //   {"Africa West": "FK"},
  //   {"Air ALM": "LM"},
  //   {"Air Algerie": "AH"},
  //   {"Air Armenia": "QN"},
  //   {"Air Astana": "KC"},
  //   {"Air Baltic": "BT"},
  //   {"Air Canada": "AC"},
  //   {"Air China": "CA"},
  //   {"Air Europa Cargo": "UX"},
  //   {"Air France": "AF"},
  //   {"Air France": "AF"},
  //   {"Air Greenland": "GL"},
  //   {"Air Hong Kong": "LD"},
  //   {"Air India": "AI"},
  //   {"Air Jamaica": "JM"},
  //   {"Air Macau": "NX"},
  //   {"Air Madagascar": "MD"},
  //   {"Air Malta": "KM"},
  //   {"Air Mauritius": "MK"},
  //   {"Air Moldova": "9U"},
  //   {"Air New Zealand": "NZ"},
  //   {"Air Niugini": "PX"},
  //   {"Air Seychelles": "HM"},
  //   {"AirBridge Cargo": "RU"},
  //   {"Alaska Airlines": "AS"},
  //   {"Alitalia": "AZ"},
  //   {"American Airlines": "AA"},
  //   {"Amerijet International": "M6"},
  //   {"Arrow Air": "JW"},
  //   {"Asiana Airlines": "OZ"},
  //   {"Atlantic Southeast Airlines": "EV"},
  //   {"Atlas Air": "5Y"},
  //   {"Austrian Cargo": "OS"},
  //   {"Avient": "SM"},
  //   {"Azerbaijan Airlines": "J2"},
  //   {"Biman Bangladesh": "BG"},
  //   {"British Airways": "BA"},
  //   {"British Midland Airways": "BD"},
  //   {"Brussels Airlines": "SN"},
  //   {"Bulgaria Air": "FB"},
  //   {"Buraq Air Transport (Arabic only)": "UZ"},
  //   {"CAL Cargo Air Lines": "5C"},
  //   {"Cameroon Airlines": "UY"},
  //   {"Canadian Airlines Int´l": "CP"},
  //   {"CargoItalia (alternate)": "2G"},
  //   {"Cargolux Airlines": "CV"},
  //   {"Cargolux Italia": "C8"},
  //   {"Caribbean Airlines": "BW"},
  //   {"Cathay Pacific Airways": "CX"},
  //   {"Cayman Airways": "KX"},
  //   {"Centurion Air Cargo": "WE"},
  //   {"China Airlines": "CI"},
  //   {"China Cargo Airlines": "CK"},
  //   {"China Eastern Airlines": "MU"},
  //   {"China Southern Airlines": "CZ"},
  //   {"Cielos Airlines": "A2"},
  //   {"Comair": "OH"},
  //   {"Condor Flugdienst": "DE"},
  //   {"Continental Airlines": "CO"},
  //   {"Copa Airlines Cargo": "CM"},
  //   {"Coyne Airways": "7C"},
  //   {"Croatia Airlines": "OU"},
  //   {"Cyprus Airways": "CY"},
  //   {"Czech Airlines": "OK"},
  //   {"DHL Aviation / European Air Transport": "QY"},
  //   {"DHL Aviation/DHL Airways": "ER"},
  //   {"Delta Air Lines": "DL"},
  //   {"Dragonair": "KA"},
  //   {"EL ALLY, ETIHAD Airways": "EY"},
  //   {"Egyptair": "MS"},
  //   {"Emirates": "EK"},
  //   {"Estonian Air": "OV"},
  //   {"Ethiopian Airlines": "ET"},
  //   {"Eva Airways": "BR"},
  //   {"Far Eastern Air Transport": "EF"},
  //   {"Fedex": "FX"},
  //   {"Finnair": "AY"},
  //   {"Florida West International Airways": "RF"},
  //   {"Garuda Indonesia": "GA"},
  //   {"Global Aviation and Services": "5S"},
  //   {"Grandstar Cargo": "GD"},
  //   {"Great Wall Airlines": "IJ"},
  //   {"Gulf Air": "GF"},
  //   {"Hainan Airlines (Chinese)": "HU"},
  //   {"Hong Kong Airlines": "N8"},
  //   {"Iberia": "IB"},
  //   {"Icelandair": "FI"},
  //   {"Indian Airlines": "IC"},
  //   {"Insel Air Cargo": "7I"},
  //   {"Iran Air": "IR"},
  //   {"JAT Airways": "JU"},
  //   {"Jade Cargo International": "JI"},
  //   {"Japan Air System": "JD"},
  //   {"Japan Airlines": "JL"},
  //   {"Jet Airways": "9W"},
  //   {"KD Avia": "KD"},
  //   {"KLM Cargo": "KL"},
  //   {"Kalitta Air": "K4"},
  //   {"Kenya Airways": "KQ"},
  //   {"Kingfisher Airlines": "IT"},
  //   {"Korean Air": "KE"},
  //   {"Kuwait Airways": "KU"},
  //   {"LACSA Airlines of Costa Rica": "LR"},
  //   {"LAN Chile": "LA"},
  //   {"LIAT Airlines": "LI"},
  //   {"LOT Polish Airlines": "LO"},
  //   {"LTU (Leisure Cargo)": "LT"},
  //   {"Lauda Air": "NG"},
  //   {"Libyan Airlines": "LN"},
  //   {"Lufthansa Cargo AG": "LH"},
  //   {"MASAir": "MY"},
  //   {"MNG Airlines": "MB"},
  //   {"Malaysian Airline System": "MH"},
  //   {"Malev Hungarian Airlines": "MA"},
  //   {"Mandarin Airlines": "AE"},
  //   {"Mario’s Air": "M2"},
  //   {"Martinair Cargo": "MP"},
  //   {"Middle East Airlines": "ME"},
  //   {"National Air Cargo": "N8"},
  //   {"Nippon Cargo Airlines": "KZ"},
  //   {"Northern Air Cargo": "NC"},
  //   {"Northwest Airlines (alternate site)": "NW"},
  //   {"Olympic Airways": "OA"},
  //   {"Pakistan Int´l Airlines": "PK"},
  //   {"Philippine Airlines": "PR"},
  //   {"Polar Air Cargo": "PO"},
  //   {"Qantas Airways": "QF"},
  //   {"Qatar Airways": "QR"},
  //   {"Royal Air Maroc": "AT"},
  //   {"Royal Brunei Airlines": "BI"},
  //   {"Royal Jordanian": "RJ"},
  //   {"SAC South American Airways": "S6"},
  //   {"SAS-Scandinavian Airlines System": "SK"},
  //   {"SATA Air Acores": "SP"},
  //   {"Saudi Arabian Airlines": "SV"},
  //   {"Shandong Airlines (Chinese)": "SC"},
  //   {"Shanghai Airlines Cargo": "F4"},
  //   {"Shanghai Airlines": "FM"},
  //   {"Shenzhen Airlines (Chinese)": "ZH"},
  //   {"Siberia Airlines": "S7"},
  //   {"Sichuan Airlines": "3U"},
  //   {"Singapore Airlines": "SQ"},
  //   {"Sky West Airlines": "OO"},
  //   {"South African Airways": "SA"},
  //   {"Southwest Airlines": "WN"},
  //   {"SriLankan Cargo": "UL"},
  //   {"Sun Express": "XQ"},
  //   {"Swiss": "LX"},
  //   {"Syrian Arab Airlines": "RB"},
  //   {"TAAG Angola Airlines": "DT"},
  //   {"TAB Cargo": "B1"},
  //   {"TACA": "TA"},
  //   {"TAM Brazilian Airlines": "JJ"},
  //   {"TAP Air Portugal": "TP"},
  //   {"TNT Airways": "3V"},
  //   {"Tampa Airlines": "QT"},
  //   {"Thai Airways": "TG"},
  //   {"Trans Mediterranean Airways": "TL"},
  //   {"Turkish Airlines": "TK"},
  //   {"UPS Air Cargo": "5X"},
  //   {"USAirways": "US"},
  //   {"Ukraine Int´l Airlines": "PS"},
  //   {"United Airlines Cargo": "UA"},
  //   {"VARIG Brazilian Airlines": "RG"},
  //   {"VARIG Brazilian Airlines": "RG"},
  //   {"Vietnam Airlines": "VN"},
  //   {"Virgin Atlantic": "VS"},
  //   {"Xiamen Airlines": "MF"},
  //   {"Yangtze River Express Airlines": "Y8"},
  //   {"Yemenia Yemen Airways": "IY"},
  //   {"more AWB tracking": "UL"}
  // ];

  Map<String, String> airlines = {
    "ABSA": "M3",
    "ANA All Nippon Cargo": "NH",
    "Adria Airways": "JP",
    "Aegean Airlines": "A3",
    "Aer Lingus Cargo": "EI",
    "AeroUnion": "6R",
    "Aeroflot": "SU",
    "Aeromexico Cargo": "AM",
    "Aeromexpress Cargo": "QO",
    "Aerosvit": "VV",
    "Africa West": "FK",
    "Air ALM": "LM",
    "Air Algerie": "AH",
    "Air Armenia": "QN",
    "Air Astana": "KC",
    "Air Baltic": "BT",
    "Air Canada": "AC",
    "Air China": "CA",
    "Air Europa Cargo": "UX",
    "Air France": "AF",
    "Air Greenland": "GL",
    "Air Hong Kong": "LD",
    "Air India": "AI",
    "Air Jamaica": "JM",
    "Air Macau": "NX",
    "Air Madagascar": "MD",
    "Air Malta": "KM",
    "Air Mauritius": "MK",
    "Air Moldova": "9U",
    "Air New Zealand": "NZ",
    "Air Niugini": "PX",
    "Air Seychelles": "HM",
    "AirBridge Cargo": "RU",
    "Alaska Airlines": "AS",
    "Alitalia": "AZ",
    "American Airlines": "AA",
    "Amerijet International": "M6",
    "Arrow Air": "JW",
    "Asiana Airlines": "OZ",
    "Atlantic Southeast Airlines": "EV",
    "Atlas Air": "5Y",
    "Austrian Cargo": "OS",
    "Avient": "SM",
    "Azerbaijan Airlines": "J2",
    "Biman Bangladesh": "BG",
    "British Airways": "BA",
    "British Midland Airways": "BD",
    "Brussels Airlines": "SN",
    "Bulgaria Air": "FB",
    "Buraq Air Transport (Arabic only)": "UZ",
    "CAL Cargo Air Lines": "5C",
    "Cameroon Airlines": "UY",
    "Canadian Airlines Int´l": "CP",
    "CargoItalia (alternate)": "2G",
    "Cargolux Airlines": "CV",
    "Cargolux Italia": "C8",
    "Caribbean Airlines": "BW",
    "Cathay Pacific Airways": "CX",
    "Cayman Airways": "KX",
    "Centurion Air Cargo": "WE",
    "China Airlines": "CI",
    "China Cargo Airlines": "CK",
    "China Eastern Airlines": "MU",
    "China Southern Airlines": "CZ",
    "Cielos Airlines": "A2",
    "Comair": "OH",
    "Condor Flugdienst": "DE",
    "Continental Airlines": "CO",
    "Copa Airlines Cargo": "CM",
    "Coyne Airways": "7C",
    "Croatia Airlines": "OU",
    "Cyprus Airways": "CY",
    "Czech Airlines": "OK",
    "DHL Aviation / European Air Transport": "QY",
    "DHL Aviation/DHL Airways": "ER",
    "Delta Air Lines": "DL",
    "Dragonair": "KA",
    "EL ALLY, ETIHAD Airways": "EY",
    "Egyptair": "MS",
    "Emirates": "EK",
    "Estonian Air": "OV",
    "Ethiopian Airlines": "ET",
    "Eva Airways": "BR",
    "Far Eastern Air Transport": "EF",
    "Fedex": "FX",
    "Finnair": "AY",
    "Florida West International Airways": "RF",
    "Garuda Indonesia": "GA",
    "Global Aviation and Services": "5S",
    "Grandstar Cargo": "GD",
    "Great Wall Airlines": "IJ",
    "Gulf Air": "GF",
    "Hainan Airlines (Chinese)": "HU",
    "Hong Kong Airlines": "N8",
    "Iberia": "IB",
    "Icelandair": "FI",
    "Indian Airlines": "IC",
    "Insel Air Cargo": "7I",
    "Iran Air": "IR",
    "JAT Airways": "JU",
    "Jade Cargo International": "JI",
    "Japan Air System": "JD",
    "Japan Airlines": "JL",
    "Jet Airways": "9W",
    "KD Avia": "KD",
    "KLM Cargo": "KL",
    "Kalitta Air": "K4",
    "Kenya Airways": "KQ",
    "Kingfisher Airlines": "IT",
    "Korean Air": "KE",
    "Kuwait Airways": "KU",
    "LACSA Airlines of Costa Rica": "LR",
    "LAN Chile": "LA",
    "LIAT Airlines": "LI",
    "LOT Polish Airlines": "LO",
    "LTU (Leisure Cargo)": "LT",
    "Lauda Air": "NG",
    "Libyan Airlines": "LN",
    "Lufthansa Cargo AG": "LH",
    "MASAir": "MY",
    "MNG Airlines": "MB",
    "Malaysian Airline System": "MH",
    "Malev Hungarian Airlines": "MA",
    "Mandarin Airlines": "AE",
    "Mario’s Air": "M2",
    "Martinair Cargo": "MP",
    "Middle East Airlines": "ME",
    "National Air Cargo": "N8",
    "Nippon Cargo Airlines": "KZ",
    "Northern Air Cargo": "NC",
    "Northwest Airlines (alternate site)": "NW",
    "Olympic Airways": "OA",
    "Pakistan Int´l Airlines": "PK",
    "Philippine Airlines": "PR",
    "Polar Air Cargo": "PO",
    "Qantas Airways": "QF",
    "Qatar Airways": "QR",
    "Royal Air Maroc": "AT",
    "Royal Brunei Airlines": "BI",
    "Royal Jordanian": "RJ",
    "SAC South American Airways": "S6",
    "SAS-Scandinavian Airlines System": "SK",
    "SATA Air Acores": "SP",
    "Saudi Arabian Airlines": "SV",
    "Shandong Airlines (Chinese)": "SC",
    "Shanghai Airlines Cargo": "F4",
    "Shanghai Airlines": "FM",
    "Shenzhen Airlines (Chinese)": "ZH",
    "Siberia Airlines": "S7",
    "Sichuan Airlines": "3U",
    "Singapore Airlines": "SQ",
    "Sky West Airlines": "OO",
    "South African Airways": "SA",
    "Southwest Airlines": "WN",
    "SriLankan Cargo": "UL",
    "Sun Express": "XQ",
    "Swiss": "LX",
    "Syrian Arab Airlines": "RB",
    "TAAG Angola Airlines": "DT",
    "TAB Cargo": "B1",
    "TACA": "TA",
    "TAM Brazilian Airlines": "JJ",
    "TAP Air Portugal": "TP",
    "TNT Airways": "3V",
    "Tampa Airlines": "QT",
    "Thai Airways": "TG",
    "Trans Mediterranean Airways": "TL",
    "Turkish Airlines": "TK",
    "UPS Air Cargo": "5X",
    "USAirways": "US",
    "Ukraine Int´l Airlines": "PS",
    "United Airlines Cargo": "UA",
    "VARIG Brazilian Airlines": "RG",
    "Vietnam Airlines": "VN",
    "Virgin Atlantic": "VS",
    "Xiamen Airlines": "MF",
    "Yangtze River Express Airlines": "Y8",
    "Yemenia Yemen Airways": "IY",
    "more AWB tracking": "UL"
  };

  void onDepartureDateChanged(value) {}
  void onDepartureDateDoneTapped(context) {
    // Navigator.push(context, MaterialPageRoute(builder: (context)=>BottomNavBar()));
  }

  // Future<void> uploadData(BuildContext context, bool isForEdit) async {
  //   if (cityCon.text.isEmpty && cityCon.text == '') {
  //     showMsg(context, 'Please provide layover city name');
  //   } else if (airportCon.text.isEmpty && airportCon.text == '') {
  //     showMsg(context, 'Please provide layover airport name');
  //   } else if (landingDateCon.text.isEmpty && landingDateCon.text == '') {
  //     showMsg(context, 'Please enter layover landing date');
  //   } else if (landingTimeCon.text.isEmpty && landingTimeCon.text == '') {
  //     showMsg(context, 'Please enter layover landing time');
  //   } else if (stayCon.text.isEmpty && stayCon.text == '') {
  //     showMsg(context, 'Please enter layover stay time');
  //   } else {
  //     try {
  //       loadingDialog(context);
  //       await profiles.doc(auth.currentUser!.uid).update({
  //         'layoverDetails': {
  //           'layoverCity': cityCon.text,
  //           'layoverAirPort': airportCon.text,
  //           'layoverLandingDate': landingDateCon.text,
  //           'layoverLandingTime': landingTimeCon.text,
  //           'layoverStayTime': landingTimeCon.text,
  //         },
  //       });
  //       print("Profile Update Successfully !");

  //       Navigator.pop(context);
  //       isForEdit
  //           ? null
  //           : Provider.of<GlobalProvider>(context, listen: false)
  //               .updateStackIndex(context, 6);
  //       isForEdit
  //           ? showMsg(
  //               context,
  //               'Successfully Updated!',
  //               bgColor: kSuccessColor,
  //             )
  //           : null;
  //       cityCon.clear();
  //       airportCon.clear();
  //       landingDateCon.clear();
  //       landingTimeCon.clear();
  //       stayCon.clear();
  //     } on FirebaseAuthException catch (e) {
  //       Navigator.pop(context);
  //       showMsg(context, e.message.toString());
  //     }
  //   }
  // }
}
